---
- name: Restart Monit
  ansible.builtin.systemd:
    name: monit
    state: restarted
  become: true

- name: Restart NetworkManager
  ansible.builtin.systemd:
    name: NetworkManager
    state: restarted
  become: true
