---

- name: Restart keepalived
  ansible.builtin.service:
    name: "{{ load_balancer_keepalived_service }}"
    state: restarted
  become: true

- name: Restart haproxy
  ansible.builtin.service:
    name: "{{ load_balancer_haproxy_service }}"
    state: restarted
  become: true

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  become: true
