---
# Handlers for reverse_proxy

- name: Restart reverse proxy
  containers.podman.podman_container:
    name: "{{ reverse_proxy_container_name }}"
    state: started
    restart: true
  become: true

- name: Restart keepalived
  ansible.builtin.service:
    name: keepalived
    state: restarted
  become: true
