---
# Handlers for reverse_proxy

- name: Restart reverse proxy
  ansible.builtin.systemd:
    name: "container-{{ reverse_proxy_container_name }}"
    state: restarted
  become: true

- name: Restart keepalived
  ansible.builtin.service:
    name: keepalived
    state: restarted
  become: true
