---
- name: "Controller TLS Preparation"
  hosts: localhost
  gather_facts: true
  become: false
  tags: [infra, tls, tls_controller]
  pre_tasks:
    - name: Load cluster init JSON # noqa: run-once
      ansible.builtin.slurp:
        src: "{{ vault_init_export_path | expanduser }}"
      register: _cluster_init_content

    - name: Set vault_root_token fact
      ansible.builtin.set_fact:
        vault_root_token: "{{ (_cluster_init_content.content | b64decode | from_json).root_token }}"
      when: _cluster_init_content.content is defined
  tasks:
    - name: Run controller-side TLS tasks
      ansible.builtin.include_role:
        name: tls
        tasks_from: controller.yml

- name: "Provision TLS Certificates"
  hosts: all
  gather_facts: true
  become: false
  tags: [infra, tls, tls_certs]
  roles:
    - role: tls
      tags: [infra, tls]

- name: "Setup Pi-hole Cluster"
  hosts: dns_cluster
  gather_facts: true
  become: false
  tags: [infra, dns]
  roles:
    - role: dns
      tags: [infra, dns]

- name: "Setup Internal Load Balancer"
  hosts: internal_lb_cluster
  gather_facts: true
  become: false
  tags: [infra, lb]
  roles:
    - role: internal_lb
      tags: [infra, lb]

- name: "Setup Edge Proxy"
  hosts: edge_proxy_cluster
  gather_facts: true
  become: false
  tags: [infra, proxy]
  roles:
    - role: edge_proxy
      tags: [infra, proxy]

- name: "Setup Artifactory"
  hosts: artifactory
  gather_facts: true
  become: false
  tags: [infra, artifactory]
  roles:
    - role: artifactory
      tags: [infra, artifactory]
