- name: "Setup Monitoring Agents (Exporters)"
  hosts: all
  gather_facts: true
  become: false
  tags: [infra, monitoring_agents, monitoring]
  roles:
    - role: prometheus_node_exporter
    - role: loki_promtail

- name: "Setup Prometheus"
  hosts: prometheus
  gather_facts: true
  become: false
  tags: [infra, prometheus, monitoring]
  roles:
    - role: prometheus

- name: "Setup Loki"
  hosts: loki
  gather_facts: true
  become: false
  tags: [infra, loki, monitoring]
  roles:
    - role: loki

- name: "Setup Grafana"
  hosts: grafana
  gather_facts: true
  become: false
  tags: [infra, grafana, monitoring]
  roles:
    - role: grafana
