---
- name: "Setup system Components"
  hosts: all
  gather_facts: true
  become: false
  tags: [system]
  roles:
    - role: facts
      tags: [system, facts]
    - role: ntp
      tags: [system, ntp]
    - role: devices_os
      tags: [system, os]
    - role: utils
      tags: [system, utils]
    - role: aur
      tags: [system, aur, aur_rebuild_yay]
    - role: firewall
      tags: [system, firewall]
    - role: containers
      tags: [system, containers]
    - role: monit
      tags: [system, monit]

- name: "Setup AMD GPU"
  hosts: homeserver
  gather_facts: true
  become: false
  tags: [system, gpu]
  roles:
    - role: gpu_amd

- name: "Setup Nvidia GPU"
  hosts: homeserver2
  gather_facts: true
  become: false
  tags: [system, gpu]
  roles:
    - role: gpu_nvidia
