---
- name: "Generate Homelab Root CA (Localhost)"
  hosts: localhost
  gather_facts: true
  become: false
  tags: [root_ca_gen]
  tasks:
    - name: Run trust role for CA generation
      ansible.builtin.import_role:
        name: trust
      vars:
        trust_stage: generate_ca
      tags: [root_ca_gen]

- name: "Distribute Homelab Root CA to All Devices"
  hosts: all
  gather_facts: false
  become: true
  tags: [trust, tls, root_ca_dist]
  tasks:
    - name: Run trust role for CA distribution
      ansible.builtin.import_role:
        name: trust
      vars:
        trust_stage: distribute_ca
      tags: [trust, tls, root_ca_dist]
