---

default_language_version:
  python: python3.14

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      # Ensure every file ends with a single newline
      - id: end-of-file-fixer
      # Convert CRLF/Mixed endings to LF
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: trailing-whitespace
      - id: check-yaml
      - id: end-of-file-fixer
      - id: check-added-large-files
        args: ['--maxkb=5000']

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.9.17
    hooks:
      - id: uv-lock

  - repo: local
    hooks:
      - id: check-ansible-vault
        name: Check for unencrypted Ansible vault files
        entry: bash -c 'for f in "$@"; do if ! grep -q "\$ANSIBLE_VAULT" "$f"; then echo "$f is not encrypted"; exit 1; fi; done' _
        language: system
        files: 'group_vars/.*vault\.yml$|host_vars/.*vault\.yml$|^vault\.yml$|roles/k3s_sealed_secret/files/sealed-secrets-key\.yaml$'
        description: Prevents unencrypted vault files from being committed.
