[project]
name = "ansible-home-cluster"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "ansible>=13.2.0",
    "ansible-lint>=26.1.1",
    "bcrypt>=5.0.0",
    "hvac>=2.4.0",
    "filelock>=3.20.3",
    "urllib3>=2.6.3",
    "black>=26.3.1"
]
