---
- name: Install Linux Headers (required for DKMS) and NVIDIA Toolkit
  community.general.pacman:
    name:
      - linux-lts
      - linux-lts-headers
      - nvidia-container-toolkit
    state: present
  become: true

- name: Check if NVIDIA packages are installed
  ansible.builtin.command: pacman -Qi {{ item }}
  loop:
    - nvidia-550xx-dkms
    - nvidia-550xx-utils
    - nvidia-550xx-settings
    - opencl-nvidia-550xx
  register: nvidia_packages_check
  failed_when: false
  changed_when: false

- name: Install Legacy NVIDIA drivers (550xx) from AUR (1080Ti)
  ansible.builtin.command:
    cmd: yay -S --noconfirm --needed nvidia-550xx-dkms nvidia-550xx-utils nvidia-550xx-settings opencl-nvidia-550xx
  become: true
  become_user: aur_builder
  when: >
    nvidia_packages_check.results | map(attribute='rc') | select('ne', 0) | list | length > 0
  register: yay_install
  changed_when: "'Packages (' in yay_install.stdout"

- name: Check if NVIDIA runtime is already configured in containerd
  ansible.builtin.command: grep -q "nvidia-container-runtime" /etc/containerd/config.toml
  register: nvidia_runtime_check
  failed_when: false
  changed_when: false
  become: true

- name: Configure NVIDIA Container Toolkit
  ansible.builtin.command:
    cmd: nvidia-ctk runtime configure --runtime containerd
  when: nvidia_runtime_check.rc != 0
  become: true
  changed_when: true
