---
- name: "Setup system Components"
  hosts: all
  gather_facts: true
  become: false
  roles:
    - role: facts
      tags: [devices, devices_system, facts]
    - role: ntp
      tags: [devices, devices_system, ntp]
    - role: devices_os
      tags: [devices, devices_system, os]
    - role: utils
      tags: [devices, devices_system, utils]
    - role: aur
      tags: [devices, devices_system, aur]
    - role: firewall
      tags: [devices, devices_system, firewall]
    - role: containers
      tags: [devices, devices_system, containers]
    - role: monit
      tags: [devices, devices_system, monit]
    - role: watchdog
      tags: [devices, devices_system, watchdog]

- name: "Setup AMD GPU"
  hosts: homeserver
  gather_facts: true
  become: false
  roles:
    - role: gpu_amd
      tags: [devices, devices_system, gpu_amd]

- name: "Setup Nvidia GPU"
  hosts: homeserver2
  gather_facts: true
  become: false
  roles:
    - role: gpu_nvidia
      tags: [devices, devices_system, gpu_nvidia]
