---
# defaults for devices_ssh (generalized)
devices_ssh_user: "{{ ansible_user | default('alarm') }}"
devices_ssh_pubkey: "{{ lookup('env', 'HOME') + '/.ssh/id_ed25519_local.pub' }}"
devices_ssh_peer_group: "{{ groups['all'] }}"
