---
- name: Deploy Traefik HelmChartConfig manifest
  ansible.builtin.template:
    src: traefik-config.yaml.j2
    dest: /var/lib/rancher/k3s/server/manifests/traefik-config.yaml
    owner: root
    group: root
    mode: '0644'
  become: true
  when: inventory_hostname == groups['server'][0]
