---
- name: Ensure keepalived conf.d directory exists
  ansible.builtin.file:
    path: /etc/keepalived/conf.d
    state: directory
    mode: '0755'

- name: Deploy K3s API Keepalived Config
  ansible.builtin.template:
    src: k3s-api.conf.j2
    dest: /etc/keepalived/conf.d/k3s-api.conf
    mode: '0644'
  notify: Restart Keepalived

- name: Deploy K3s LB Keepalived Config
  ansible.builtin.template:
    src: k3s-lb.conf.j2
    dest: /etc/keepalived/conf.d/k3s-lb.conf
    mode: '0644'
  notify: Restart Keepalived
