---
loki_promtail_image: "{{ loki_promtail_image | default('docker.io/grafana/promtail:latest') }}"
loki_promtail_container_name: promtail
loki_promtail_config_dir: /etc/promtail
loki_promtail_http_listen_port: 9080

# Loki address - using the internal IP directly for metrics/logs backends
loki_url: "http://{{ hostvars[groups['loki'][0]].ansible_host | default('127.0.0.1') }}:{{ loki_port | default(3100) }}/loki/api/v1/push"

loki_promtail_scrape_configs:
  - job_name: system
    type: static
    path: "/var/log/*log"
    labels:
      job: varlogs
  - job_name: journal
    type: journal
    labels:
      job: journal
