---
- name: "Setup K3s Load Balancer"
  hosts: server
  gather_facts: true
  become: true
  tags: [k3s, k3s_infrastructure, k3s_lb]
  roles:
    - role: k3s_lb
      tags: [k3s, k3s_infrastructure, k3s_lb]
