---
watchdog_runtime_timeout: "30"
watchdog_shutdown_timeout: "10min"
watchdog_ping_hosts:
  - "8.8.8.8"
  - "1.1.1.1"
watchdog_ping_count: 5
watchdog_retry_timeout: 90
watchdog_interval: 10
watchdog_realtime: "yes"
watchdog_device: "/dev/watchdog"
watchdog_interface: "{{ ansible_default_ipv4.interface | default('end0') }}"
