---
vault_image: hashicorp/vault:1.21.1
vault_api_port: "{{ global_vault_api_port | default(18200) }}"
vault_cluster_port: "{{ global_vault_cluster_port | default(18201) }}"
vault_acme_require_eab: false

# Controller vault password path (used by run.sh)
controller_vault_password_file: "~/.vault_pass"

# Stable advertise addr for ACME (avoid redirects to leader hostname)
vault_acme_advertise_addr: "{{ load_balancer_virtual_ip }}"
vault_transit_tls_skip_verify: true
