---

# Virtual IP managed by keepalived for the load balancer cluster
load_balancer_virtual_ip: "192.168.0.253"
load_balancer_vip_prefixlen: 24
load_balancer_virtual_router_id: 53

# HAProxy defaults
load_balancer_enable_nonlocal_bind: true
load_balancer_haproxy_package: haproxy
load_balancer_keepalived_package: keepalived

# Service names
load_balancer_haproxy_service: haproxy
load_balancer_keepalived_service: keepalived

# VRRP Defaults
load_balancer_vrrp_auth_pass: "secret-lb"

load_balancer_haproxy_frontends: []
load_balancer_haproxy_backends: []

# Optional: HAProxy peers for stick-table sync
load_balancer_haproxy_peers_enabled: false
load_balancer_haproxy_peers_name: lb-peers
load_balancer_haproxy_peers: []
