---
# handlers for ntp role

- name: Restart chronyd
  ansible.builtin.systemd:
    name: chronyd
    state: restarted
  become: true

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  become: true
