---
# handlers for ntp role

- name: Restart ntpd
  ansible.builtin.systemd:
    name: ntpd.service
    state: restarted
  become: true

- name: Restart systemd-timesyncd
  ansible.builtin.systemd:
    name: systemd-timesyncd
    state: restarted
  become: true

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  become: true
