---

# specific args for server nodes (Control Plane)
extra_server_args: >-
  --prefer-bundled-bin
  --disable traefik
  --flannel-backend=vxlan
  --kubelet-arg=system-reserved=cpu=1000m,memory=2Gi
  --kubelet-arg=kube-reserved=cpu=1000m,memory=3Gi
  --kubelet-arg=max-pods=110
  --kube-apiserver-arg=max-requests-inflight=200
  --kube-apiserver-arg=max-mutating-requests-inflight=100
  --tls-san {{ k3s_api_vip }}
  --tls-san {{ api_endpoint }}
  --tls-san api.k3s.{{ base_domain }}
  --advertise-address {{ ansible_host }}
  --node-ip {{ ansible_host }}
  --etcd-arg=quota-backend-bytes=8589934592
  --etcd-arg=auto-compaction-mode=periodic
  --etcd-arg=auto-compaction-retention=1h
  --etcd-arg=heartbeat-interval=500
  --etcd-arg=election-timeout=5000
