---
- name: "Podman Container Status"
  hosts: all
  gather_facts: false
  become: false
  tags: [health, container_status]
  tasks:
    - name: Get User Podman Containers
      ansible.builtin.command: >
        podman ps -a --format "table {{ '{{' }}.Names{{ '}}' }}\t{{ '{{' }}.Status{{ '}}' }}\t{{ '{{' }}.Image{{ '}}' }}"
      register: _user_podman_ps
      changed_when: false
      failed_when: false

    - name: Get Root Podman Containers
      ansible.builtin.command: >
        podman ps -a --format "table {{ '{{' }}.Names{{ '}}' }}\t{{ '{{' }}.Status{{ '}}' }}\t{{ '{{' }}.Image{{ '}}' }}"
      register: _root_podman_ps
      changed_when: false
      failed_when: false
      become: true # Use Ansible privilege escalation instead of manual sudo
