---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

- name: Restart Postgres
  ansible.builtin.systemd:
    name: "container-{{ postgres_container_name }}"
    state: restarted
    daemon_reload: true
  become: true

- name: Restart haproxy
  ansible.builtin.service:
    name: "{{ postgres_haproxy_service }}"
    state: restarted
  become: true
