---
- name: Ensure loki group exists
  ansible.builtin.group:
    name: "{{ loki_group }}"
    gid: "{{ loki_gid }}"
    state: present
    system: true
  become: true

- name: Ensure loki user exists
  ansible.builtin.user:
    name: "{{ loki_user }}"
    uid: "{{ loki_uid }}"
    group: "{{ loki_group }}"
    home: "{{ loki_home }}"
    create_home: yes
    state: present
    system: true
    shell: /usr/sbin/nologin
  become: true

- name: Ensure directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ loki_user }}"
    group: "{{ loki_group }}"
    mode: '0755'
  loop:
    - "{{ loki_config_dir }}"
    - "{{ loki_data_dir }}"
  become: true

- name: Deploy loki configuration
  ansible.builtin.template:
    src: loki-config.yml.j2
    dest: "{{ loki_config_dir }}/loki-config.yml"
    owner: "{{ loki_user }}"
    group: "{{ loki_group }}"
    mode: '0644'
  become: true
  notify: Restart loki

- name: Run loki container
  containers.podman.podman_container:
    name: "{{ loki_container_name }}"
    image: "{{ loki_image }}"
    state: started
    user: "{{ loki_uid }}:{{ loki_gid }}"
    restart_policy: always
    dns:
      - "{{ pihole_virtual_ip | default('192.168.0.251') }}"
    publish:
      - "{{ loki_port }}:3100"
    volumes:
      - "{{ loki_config_dir }}/loki-config.yml:/etc/loki/local-config.yaml:Z"
      - "{{ loki_data_dir }}:/loki:Z"
    command:
      - "-config.file=/etc/loki/local-config.yaml"
  become: true
