---
- name: Copy Homelab Root CA to system anchor path
  ansible.builtin.copy:
    src: "{{ root_ca_cert_controller | expanduser }}"
    dest: "{{ tls_root_ca_anchor_path }}"
    owner: root
    group: root
    mode: '0644'
  notify: Refresh system trust store
