---
# handlers for pihole

- name: Restart keepalived
  ansible.builtin.service:
    name: keepalived
    state: restarted
  become: true

- name: Restart pihole dns
  ansible.builtin.command: podman exec {{ pihole_container_name }} pihole reloaddns
  become: false
  changed_when: false
  check_mode: no
