---
# Handlers for Vault role

- name: Restart Vault container to apply config changes (if needed)
  containers.podman.podman_container:
    name: "{{ vault_container_name }}"
    image: "{{ vault_image }}"
    state: started
    restart: true
  become: true

- name: Refresh system trust store
  ansible.builtin.command: update-ca-trust extract
  changed_when: true
  become: true
  listen: "Refresh system trust store"
