---
# tasks file for jetson-stats

- name: Install jetson-stats (Ubuntu/Debian)
  pip:
    name: jetson-stats
  become: true
  when: ansible_facts['os_family'] == "Debian"

- name: Enable service (Ubuntu/Debian)
  systemd:
    name: jtop.service
    enabled: true 
    state: started
  become: true
  when: ansible_facts['os_family'] == "Debian"
