---
# tasks file for prometheus

- name: Install prometheus (Arch)
  pacman:
    name: prometheus
    state: latest
  become: true
  when: ansible_distribution == 'Archlinux'

- name: Install prometheus (Ubuntu/Debian)
  apt:
    name: prometheus
    state: latest
  become: true
  when: ansible_facts['os_family'] == "Debian"

- name: copy Prometheus main config file
  template:
    src: "prometheus.yml.j2"
    dest: "/etc/prometheus/prometheus.yml"
  become: true

- name: Create rules directory
  file:
    path: /etc/prometheus/rules/
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: '0755'
    state: directory
  become: true

- name: copy Prometheus rules file
  copy:
    src: "rules.yml"
    dest: "/etc/prometheus/rules/"
  become: true

- name: Enable prometheus service
  systemd:
    name: prometheus
    state: started
    daemon_reload: yes
    enabled: true 
  become: true
