---
# tasks file for common

- name: Set locale
  locale_gen:
    name: "{{ item }}"
    state: present
  become: true
  loop:
    - en_US.UTF-8
    - fr_BE.UTF-8
    - C.UTF-8

- name: Install dependencies (Ubuntu/Debian)
  apt:
    state: latest
    name:
      - curl
      - wget
      - git
      - silversearcher-ag
      - logrotate
      - syslog-ng
      - ranger
      - tzdata
      - htop
      - python3-pip
      - jq
      - ncdu
  become: true
  when: ansible_facts['os_family'] == "Debian"

- name: Install dependencies (Arch)
  pacman:
    state: latest
    name:
      - curl
      - wget
      - git
      - the_silver_searcher
      - logrotate
      - syslog-ng
      - ranger
      - bpytop
      - python-pip
      - jq
      - ncdu
  become: true
  when: ansible_distribution == 'Archlinux'

- name: Update hostname
  hostname:
    name: "{{ inventory_hostname }}"
  become: true

- name: Set timezone
  timezone:
    name: Europe/Brussels
  become: true

- name: Add IP address of all hosts to all hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item }}$'
    line: "{{ hostvars[item].ansible_host }} {{item}}"
    state: present
  become: true
  when: hostvars[item].ansible_host is defined
  with_items: "{{ groups.all }}"

- name: "Create group {{ target_user }}"
  group:
    name: "{{ target_user }}"
    state: present
  become: true

- name: "Define role executed var {{ role_name }}_was_executed"
  set_fact:
    "{{ role_name }}_was_executed": true
    cacheable: true
