---
# tasks file for devices_os (refactored from os_setup)

- name: Ensure Ansible remote tmp exists with safe perms
  ansible.builtin.file:
    path: /tmp/.ansible-tmp
    state: directory
    mode: "1777"
    owner: root
    group: root
  become: true

- name: Set locale
  community.general.locale_gen:
    name: "en_GB.UTF-8"
    state: present
  become: true

- name: Update hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
  become: true

- name: Set timezone
  community.general.timezone:
    name: Europe/Brussels
  become: true

- name: "Create group {{ target_user }}"
  ansible.builtin.group:
    name: "{{ target_user }}"
    state: present
  become: true
