---
- name: Create ArgoCD namespace
  ansible.builtin.command: k3s kubectl create namespace {{ argocd_namespace }}
  delegate_to: "{{ groups['server'][0] }}"
  run_once: true
  become: true
  register: _argocd_ns
  failed_when: _argocd_ns.rc != 0 and 'already exists' not in _argocd_ns.stderr
  changed_when: _argocd_ns.rc == 0

- name: Install ArgoCD HA
  ansible.builtin.command: >-
    k3s kubectl apply -k {{ path_to_gitops_repo }}//bootstrap/argocd?ref=main
  delegate_to: "{{ groups['server'][0] }}"
  run_once: true
  become: true
  register: _argocd_install
  changed_when: "'created' in _argocd_install.stdout or 'configured' in _argocd_install.stdout"

- name: Wait for ArgoCD server to be ready
  ansible.builtin.command: k3s kubectl wait --for=condition=available --timeout=300s deployment/argocd-server -n {{ argocd_namespace }}
  delegate_to: "{{ groups['server'][0] }}"
  run_once: true
  become: true
  changed_when: false

- name: Wait for argocd-notifications-secret to be available
  ansible.builtin.command: >-
    k3s kubectl get secret argocd-notifications-secret -n {{ argocd_namespace }}
  register: _argocd_notifications_secret_check
  until: _argocd_notifications_secret_check.rc == 0
  retries: 30
  delay: 10
  delegate_to: "{{ groups['server'][0] }}"
  run_once: true
  become: true
  changed_when: false

- name: Annotate argocd-notifications-secret
  ansible.builtin.command: >-
    k3s kubectl annotate secret argocd-notifications-secret -n {{ argocd_namespace }} sealedsecrets.bitnami.com/managed="true" --overwrite
  delegate_to: "{{ groups['server'][0] }}"
  run_once: true
  become: true
  when: _argocd_notifications_secret_check.rc == 0
  changed_when: true

- name: Wait for argocd-secret to be available
  ansible.builtin.command: >-
    k3s kubectl get secret argocd-secret -n {{ argocd_namespace }}
  register: _argocd_secret_check
  until: _argocd_secret_check.rc == 0
  retries: 30
  delay: 10
  delegate_to: "{{ groups['server'][0] }}"
  run_once: true
  become: true
  changed_when: false

- name: Annotate argocd-secret to allow Sealed Secrets adoption
  ansible.builtin.command: >-
    k3s kubectl annotate secret argocd-secret -n {{ argocd_namespace }} sealedsecrets.bitnami.com/managed="true" --overwrite
  delegate_to: "{{ groups['server'][0] }}"
  run_once: true
  become: true
  when: _argocd_secret_check.rc == 0
  changed_when: true

- name: Patch ArgoCD Server Deployment with hostAliases for Authelia
  ansible.builtin.command: >-
    k3s kubectl patch deployment argocd-server -n {{ argocd_namespace }} --patch
    '{"spec": {"template": {"spec": {"hostAliases": [{"ip": "{{ reverse_proxy_virtual_ip }}",
    "hostnames": ["auth.k3s.gillouche.homelab"]}]}}}}'
  delegate_to: "{{ groups['server'][0] }}"
  run_once: true
  become: true
  changed_when: true
