---
# tasks file for base

- name: Allow yay and pacman to run sudo without passwd
  lineinfile:
    dest: /etc/sudoers
    line: "alarm ALL=(ALL) NOPASSWD: /usr/bin/yay, /usr/bin/pacman"
    state: present
  become: true
  when: ansible_facts['os_family'] == "Archlinux"

- name: Allow apt to run sudo without passwd
  lineinfile:
    dest: /etc/sudoers
    line: "jetson ALL=(ALL) NOPASSWD: /usr/bin/apt"
    state: present
  become: true
  when: ansible_facts['os_family'] == "Debian"

- name: "Install base dependencies"
  pacman:
    name: ["go", "git", "make", "gcc", "patch", "sudo"]
    state: present
  become: true
  when: ansible_facts['os_family'] == "Archlinux"

- name: "Define role executed var {{ role_name }}_was_executed"
  set_fact:
    "{{ role_name }}_was_executed": true
    cacheable: true
