---
prometheus_user: prometheus
prometheus_group: prometheus
prometheus_uid: 10001
prometheus_gid: 10001
prometheus_home: /home/prometheus
prometheus_config_dir: "{{ prometheus_home }}/config"
prometheus_data_dir: /mnt/data/prometheus
prometheus_image: quay.io/prometheus/prometheus:latest
prometheus_container_name: prometheus
prometheus_port: 9090
