---
# ==============================================================================
# K3s Cluster Orchestrator
# ==============================================================================

# k3s: k3s cluster
- name: K3s install
  import_playbook: includes/setup/k3s.yml
  tags: [k3s]
