---
# ==============================================================================
# Controller Reset Playbook (macOS / Localhost)
# ==============================================================================
# separate playbook because it needs -K, different password than cluster's sudo user

- name: Reset Controller DNS
  import_playbook: includes/reset/reset_controller_dns.yml
  tags: [reset_controller_dns]

- name: Reset TLS Controller (Homelab Root CA)
  import_playbook: includes/reset/reset_controller_tls.yml
  tags: [reset_controller_tls]
