---
kube_state_metrics_namespace: "kube-system"
kube_state_metrics_chart_version: "7.0.0"

k3s_dashboard_namespace: "kubernetes-dashboard"
k3s_dashboard_chart_version: "7.14.0"
k3s_dashboard_node_port: 30443
k3s_dashboard_token_path: "~/.local/share/ansible-home-cluster/k3s-dashboard-token.json"
