---
systemd_dir: /etc/systemd/system

# Collection variables
use_external_database: true
api_endpoint: "{{ k3s_api_vip }}" # Using the VIP for the endpoint
api_port: 6443

# Database Configuration
k3s_db_user: "{{ global_k3s_db_user }}"
k3s_db_name: "{{ global_k3s_db_name }}"
k3s_db_host: "{{ global_k3s_db_host }}"
k3s_db_port: "{{ global_k3s_db_port }}"
k3s_db_password: "{{ global_k3s_db_password }}"

# K3s Version
k3s_version: "{{ global_k3s_version | default('v1.31.2+k3s1') }}"

# Escape $ for systemd unit files
datastore_endpoint: "postgres://{{ k3s_db_user }}:{{ k3s_db_password | replace('$', '$$') }}@{{ k3s_db_host }}:{{ k3s_db_port }}/{{ k3s_db_name }}"

# Define a static token for the cluster to avoid propagation issues during setup
# In a real-world scenario, this should be moved to a vault file.
k3s_cluster_token: "k3s-ansible-cluster-token-static"

# Keepalived Configuration for K3s API
k3s_api_vip_prefixlen: 24
k3s_api_virtual_router_id: 64
k3s_api_vrrp_interface: "{{ monit_network_interface | default('end0') }}"
k3s_vrrp_auth_pass: "{{ vault_k3s_vrrp_auth_pass | default('k3s-vrrp-secret') }}"

# Keepalived Configuration for K3s Service LB
k3s_lb_vip_prefixlen: 24
k3s_lb_virtual_router_id: 65
k3s_lb_vrrp_interface: "{{ monit_network_interface | default('end0') }}"
